//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furnitura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furnitura()
        {
            this.FurnituraIzdeliya = new HashSet<FurnituraIzdeliya>();
            this.SkladFurnituri = new HashSet<SkladFurnituri>();
            this.Tip = new HashSet<Tip>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public double Shirina { get; set; }
        public Nullable<double> Dlina { get; set; }
        public decimal Cena { get; set; }
        public Nullable<double> Ves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnituraIzdeliya> FurnituraIzdeliya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladFurnituri> SkladFurnituri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tip> Tip { get; set; }
    }
}
