//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnituraIzdeliya
    {
        public int Id { get; set; }
        public string IdFurnitura { get; set; }
        public string IdIzdeliya { get; set; }
        public string Razmeshchenie { get; set; }
        public int Kolichestvo { get; set; }
        public string Povorot { get; set; }
    
        public virtual Furnitura Furnitura { get; set; }
        public virtual Izdeliya Izdeliya { get; set; }
    }
}
