//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdeliya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdeliya()
        {
            this.FurnituraIzdeliya = new HashSet<FurnituraIzdeliya>();
            this.TkaniIzdeliya = new HashSet<TkaniIzdeliya>();
            this.ZakazniyeIzdeliya = new HashSet<ZakazniyeIzdeliya>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public double Shirina { get; set; }
        public double Dlina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnituraIzdeliya> FurnituraIzdeliya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TkaniIzdeliya> TkaniIzdeliya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazniyeIzdeliya> ZakazniyeIzdeliya { get; set; }
    }
}
